### ISSUE TITLE
Build and deploy the latest environment image

### ISSUE THREAD

**Issue by choldgraf** [utoronto-2i2c/jupyterhub-deploy#106]
### Description

In https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/105 I updated our TZ variable so that it is properly set. However, I forgot that image builds aren't automatically happening (because of https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/79).

### Tasks

We need to do the following:

- [x] build the environment for this repository and push it to the registry
- [x] update staging to use the image
- [x] double-check that the issue is resolved by running `library(tidyverse)` and confirming that there is no error about `timedatectl`
- [x] If no error, do the same for `prod`

I wonder if @GeorgianaElena would be willing to give this a shot in tandem with deploying #101 as well? (@yuvipanda updated the credentials so we should be able to deploy just fine now)

**Comment by GeorgianaElena** [comment]
`library(tidyverse)` returns this now:
![tidyverse-error](https://user-images.githubusercontent.com/7579677/134489697-dd7299d2-a568-49ac-b1e8-ad9818c67479.png)

**Comment by choldgraf** [comment]
@GeorgianaElena i think that is correct! Those conflicts messages were expected, i believe

**Comment by choldgraf** [comment]
this is now fixed with #113
