### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by yuvipanda** [utoronto-2i2c/jupyterhub-deploy#22]
Things we should do before we can consider this 'go'

- [x] Finalize what attribute we're going to use for usernames. Currently at `oid`, although that isn't human readable. Trying for verified_secondary_email, since email is changeable
- [x] Setup CNAME from jupyter.utoronto.ca to utoronto.2i2c.cloud. We'll provision HTTPS certs ourselves, and the CNAME gives us flexibility in setting IP addresses ourselves.
- [x] Make the home page more palatable. Can be done so by modifying https://github.com/utoronto-2i2c/homepage
- [x] Test out the user image, and make sure folks can use it for their classes

Things that I want to happen parallel to this, but not blockers

- [x] Start collecting operational metrics with prometheus / grafana
- [x] Size the cluster appropriately to begin with based on expected usage, and tune autoscaling parameters.
- [x] Make sure CI / CD works for deploys
- [x] Use Azure Container Registry for images

**Comment by yuvipanda** [comment]
For userid, we examined the following attributes:
- upn / primary_email - these two seemed to be the same, and could change at any time
- secondary_verified_email - this is a *list* of emails, not just a single email. This *almost* gives us utorid, but doesn't quite - seems to be inconsistent
- oid is opaque, but is consistent.  https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#using-claims-to-reliably-identify-a-user-subject-and-object-id recommends using it.

So even though I don't like using an opaque identifier, I think that's the way to go here. We'll have to add 'display_name' functionality to JupyterHub.

Thanks a lot to Tanya Shattuck for digging in and exploring all options!

**Comment by yuvipanda** [comment]
This is done!
